exclude: "(third_party)"
repos:
 - repo: local
   hooks:
    - id: custom-script-file
      name: custom-script-file
      language: script
      entry: tools/check_license.sh
      files: (.*\.(c|cpp|h|hpp|fbs|sh|py)|Dockerfile|cmake|txt|Makefile)$
    - id: clang-format
      name: clang-format
      description: Format files with ClangFormat.
      entry: clang-format-14
      language: system
      types_or: [c, c++]
      exclude: "(parson|schemas)"
      args: ["-i", "--style=file"]

 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
    - id: trailing-whitespace
      exclude_types: [markdown, yaml, json]
      exclude: |
        (?x)^(
          LICENSE|
          .devcontainer/devcontainer.json|
          .devcontainer/initializeCommand.cmd|
          .devcontainer/initializeCommand.sh
        )$
    - id: end-of-file-fixer
      exclude_types: [markdown, yaml, json]
      exclude: |
        (?x)^(
          LICENSE|
          .devcontainer/devcontainer.json|
          .devcontainer/initializeCommand.cmd|
          .devcontainer/initializeCommand.sh
        )$
