= Vision and Sensing pass:[<br/>] Application SDK pass:[<br/>] Console API Initialize pass:[<br/>] Functional Specifications pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc1: AITRIOS™ and AITRIOS logos are the registered trademarks or trademarks
:trademark-desc2: of Sony Group Corporation or its affiliated companies.
:toc:
:toc-title: TOC
:toclevels: 1
:chapter-label:
:lang: en

== Change history

|===
|Date |What/Why

|2023/01/30
|Initial draft

|===

== Terms/Abbreviations
|===
|Terms/Abbreviations |Meaning 

|Console REST API
|REST API provided by Console for AITRIOS

|Console Access Library
|Libraries for using the features of the Console REST API. There is one for Python and another for TypeScript, but for the purposes of this document, it is meant for Python.

|===

== Reference materials

* Portal User Manual +
** https://developer.aitrios.sony-semicon.com/development-guides/documents/manuals/

[[anchor-ref]]
* API Reference
** https://developer.aitrios.sony-semicon.com/development-guides/reference/api-references/

* Console Access Library Functional Specifications
** https://developer.aitrios.sony-semicon.com/development-guides/documents/specifications/

== Expected use case
* You want to use Console for AITRIOS through API
** Example: Import AI models and post-process applications into Console for AITRIOS and deploy them to edge AI devices through API
* You want to authenticate to use the API

[[anchor-operation]]
== Functional overview/Algorithm
=== Functional overview
* SDK provides notebook for system client authentication to Console for AITRIOS

<<<

[mermaid]
----
flowchart TD;
    %% definition
    classDef object fill:#FFE699, stroke:#FFD700
    style legend fill:#FFFFFF, stroke:#000000

    %% impl
    subgraph legend["Legend"]
        process(Processing/User behavior)
    end
----


* Flow overview
+
[mermaid]
----
flowchart TD
    start((Start)) --> id1(1.Get connection information)
    id1 --> id2(2.Create and edit the configuration file)
    id2 --> id3(3.Run the notebook)
    id3 --> finish(((Finish)))
----


. Get connection information
** Get credentials needed to connect to AITRIOS

. Create and edit the configuration file
** Create the configuration file and set the information gotten in 1

. Run the notebook
** Run the notebook to authenticate to AITRIOS

* See next chapter for details on each flow

== User interface specifications
=== Prerequisite
* You have registered as a user through Portal for AITRIOS and participated in the AITRIOS project

=== How to start each function
. Jump to the `**README.md**` in the `**set_up_console_client**` directory from the hyperlink in the `**README.md**` in the directory for each feature that uses the Console Access Library

=== Get connection information
Get the following information to connect to Console for AITRIOS using the API: + 
This information is used in <<anchor-edit, _Create and edit the configuration file_>> of the next section.

* Server URL + 
Check the following from the documentation of this function (`**README.md**`) :
** API server base URL
** Authentication server URL

* Client app details + 
Get from the list of client apps in Portal for AITRIOS: + 
See https://developer.aitrios.sony-semicon.com/development-guides/documents/manuals[Portal User Manual] for details.

** Client ID
** Secret

[[anchor-edit]]
=== Create and edit the configuration file
Create the <<anchor-conf, _configuration file_>> in the `**set_up_console_client**` directory, and set the preceding connection information.

NOTE: All parameters are required.

NOTE: The parameters passed to the Console Access Library API are as specified in the <<anchor-ref, _Console Access Library API_>>.

[[anchor-conf]]
|===
|Configuration |Meaning |Range |Remarks

|`**console_endpoint**`
|API server base URL
|String +
Details follow the Console Access Library API specification.
|Don't abbreviate +
Used for the following Console Access Library API +
・`**common.config.Config**`

|`**portal_authorization_endpoint**`
|Authentication server URL
|String +
Details follow the Console Access Library API specification.
|Don't abbreviate +
Used for the following Console Access Library API +
・`**common.config.Config**`

|`**client_id**`
|Client ID required for authentication
|String +
Details follow the Console Access Library API specification.
|Don't abbreviate +
Used for the following Console Access Library API +
・`**common.config.Config**`

|`**client_secret**`
|Secret required for authentication
|String +
Details follow the Console Access Library API specification.
|Don't abbreviate +
Used for the following Console Access Library API +
・`**common.config.Config**`

|===

=== Run the notebook
. Open the notebook, _*.ipynb_, in the directory for client authentication under the `**common**` directory, and run the python scripts in it
** The script does the following:
*** Checks that <<anchor-conf, _configuration file_>> exists in the execution directory
**** If an error occurs, the error description is displayed and running is interrupted.
*** Checks that <<anchor-conf, _configuration file_>> includes each parameter
**** If an error occurs, the error description is displayed and running is interrupted.
*** Reads the value of each parameter from <<anchor-conf, _configuration file_>> to call API for system client authentication
**** If an error occurs, the error description is displayed and running is interrupted.
**** If authentication succeeds and the client instance is created successfully, displays a successful message
*** Saves the client instance for use by other notebooks in the SDK
** See https://developer.aitrios.sony-semicon.com/development-guides/documents/specifications/[Cloud SDK Console Access Library(Python) Functional Specifications] for details on errors and response times

<<<

=== Sequence

[mermaid]
----
%%{init:{'themeVariables':{'fontSize':'24px'}, 'themeCSS':'text.actor {font-size:18px !important;} .messageText {font-size:18px !important;}'}}%%
sequenceDiagram
    participant user as User
    participant portal as Portal<br>for AITRIOS
    participant container as Dev Container
    participant access_lib as Console Access<br>Library
    participant auth_server as Authentication<br>server

    user ->>portal : Access<br>Web UI
    portal ->>user : Display<br>client ID/secret
    user->>container: Create and edit<br>the configuration file
    user->>container: Run the notebook
    container->> access_lib: Generate a<br>Config instance
    access_lib-->>container: Response<br>※In case of success<br>Config instance
    container->> access_lib: Run the API<br>to get access token
    access_lib->>auth_server: Authentication<br>request
    auth_server-->>access_lib: Response
    access_lib-->>container: Response
    container->>user: Results<br>(Access token acquisition<br>success/failure)
    container->>access_lib: Generate a<br>Client instance
    access_lib-->>container: Response<br>※In case of success<br>Client instance
    container->>user: Results<br>(Client generation<br>success/failure)
----


== Target performances/Impact on performances
* Users can take advantage of each feature of the Console for AITRIOS API without being aware of its internal operation
* UI response time of 1.2 seconds or less
* If processing takes more than 5 seconds, then the display during processing can be updated sequentially
* Provides users with documentation of usage tools and version information

== Assumption/Restriction
* None

== Remarks
* None

== Unconfirmed items
* None

