#!/usr/bin/env bash
# Copyright 2022 Sony Semiconductor Solutions Corp. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

# checkout git submodules before container creation at starting devcontainer/codespaces only first time.
# (below if statement checking is a workaround of git CVE-2022-24765)
if [[ ! "$(ls -A $PWD/.devcontainer/dependencies/aitrios-sdk-console-access-lib-python)" ]]
then
    git submodule update --init --recursive $PWD/.devcontainer/dependencies/aitrios-sdk-console-access-lib-python
fi
if [[ ! "$(ls -A $PWD/.devcontainer/dependencies/aitrios-sdk-zone-detection-webapp-cs)" ]]
then
    git submodule update --init --recursive $PWD/.devcontainer/dependencies/aitrios-sdk-zone-detection-webapp-cs
fi